### ISSUE TITLE
pyglet 1.4.7 issue?

### ISSUE THREAD

**Issue by podstanar** [Kautenja/nes-py#63]
On Win 10 x64 + Python 3.7.5, running **nes_py -h** produces this:

```
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyglet 1.4.7 (c:\python37\lib\site-packages), Requirement.parse('pyglet<=1.3.2,>=1.2.0'), {'gym'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\Scripts\nes_py-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3250, in <module>
    @_call_aside
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyglet 1.4.7 (c:\python37\lib\site-packages), Requirement.parse('pyglet<=1.3.2,>=1.2.0'), {'gym'})
```

**Comment by podstanar** [comment]
Solved by:
```
pip uninstall pyglet
pip install -I pyglet==1.3.2
```
