### ISSUE TITLE
ImportError when using nes_py.wrappers/JoypadSpace

### ISSUE THREAD

**Issue by kshitij86** [Kautenja/nes-py#65]
### Describe the bug

ImportError: cannot import name 'Env' when using JoypadSpace.

### To Reproduce

Code from [gym_super_mario_bros pypi documentation](https://pypi.org/project/gym-super-mario-bros/) :

```
from nes_py.wrappers import JoypadSpace
import gym_super_mario_bros
from gym_super_mario_bros.actions import SIMPLE_MOVEMENT
env = gym_super_mario_bros.make('SuperMarioBros-v0')
env = JoypadSpace(env, SIMPLE_MOVEMENT)

done = True
for step in range(5000):
    if done:
        state = env.reset()
    state, reward, done, info = env.step(env.action_space.sample())
    env.render()

env.close()
```

### Expected behavior

Start a new gym environment using nes_py and render a few games on-screen.

### Environment

-   Operating System: Ubuntu 18.04.2 LTS
-   Python version: Python 3.6.9
-   C++ compiler and version: gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

### Additional context

Full stacktrace:
```Traceback (most recent call last):
  File "{...}/Desktop/openai-gym/gym.py", line 1, in <module>
    from nes_py.wrappers import JoypadSpace
  File "{...}/venv/lib/python3.6/site-packages/nes_py/__init__.py", line 2, in <module>
    from .nes_env import NESEnv
  File "{...}/venv/lib/python3.6/site-packages/nes_py/nes_env.py", line 7, in <module>
    import gym
  File "{...}/openai-gym/gym.py", line 1, in <module>
    from nes_py.wrappers import JoypadSpace
  File "{...}/venv/lib/python3.6/site-packages/nes_py/wrappers/__init__.py", line 2, in <module>
    from .joypad_space import JoypadSpace
  File "{...}/venv/lib/python3.6/site-packages/nes_py/wrappers/joypad_space.py", line 3, in <module>
    from gym import Env
ImportError: cannot import name 'Env'
```

**Comment by Kautenja** [comment]
running the script on my machine does not reproduce the issue. In python3 with the latest gym installed i can run `from gym import Env` with no problem. Try updating gym.
