### ISSUE TITLE
Undefined symbol "_ZTVSt9basic_iosIcSt11char_traitsIcEE"

### ISSUE THREAD

**Issue by ManPython** [Kautenja/nes-py#97]
### Describe the bug

```
Traceback (most recent call last):
  File "/usr/home/ManPython/venvpython311/bin/nes_py", line 5, in <module>
    from nes_py.app.cli import main
  File "/usr/home/ManPython/venvpython311/lib/python3.11/site-packages/nes_py/__init__.py", line 2, in <module>
    from .nes_env import NESEnv
  File "/usr/home/ManPython/venvpython311/lib/python3.11/site-packages/nes_py/nes_env.py", line 23, in <module>
    _LIB = ctypes.cdll.LoadLibrary(glob.glob(_LIB_PATH)[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /usr/home/ManPython/venvpython311/lib/python3.11/site-packages/nes_py/lib_nes_env.cpython-311.so: Undefined symbol "_ZTVSt9basic_iosIcSt11char_traitsIcEE"
```

### To Reproduce

1. nes_py -r E:\roms\1.nes

### Expected behavior

Run simple mario game.

### Environment

-   Operating System: W11
-   Python version: 311
-   C++ compiler and version:
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x86
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64

### Additional context

nes_py-8.2.1.tar.gz

**Comment by Kautenja** [comment]
Thanks for the detailed report. I checked the current maintained branch, and this error is also coming from the older ctypes-based lib_nes_env loading path from nes-py 8.2.1. The package has since been reworked to import the native emulator through nes_py._native instead, and the old ctypes shared-library discovery path is gone. Since the failing path from this report is no longer part of the maintained implementation, I am closing this out. If anyone can reproduce a comparable import/linking failure on the current supported release and support matrix, please open a fresh issue with the exact version, platform, and logs.
